// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tinput: typeof import('./src/components/todo/Tinput.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TList: typeof import('./src/components/todo/TList.vue')['default']
    YuStore: typeof import('./src/components/YuStore.vue')['default']
  }
}
